"use client";
import {useEffect,useState} from "react";
const STORE="link-genesis-drafts-v1";
const fields=[["pain","Dolor que resolvemos"],["model","Modelo y propuesta de valor"],["buyer","Quién compra"],["seller","Quién vende"],["operator","Quién opera"],["issuer","Quién factura"],["artifact","Artefacto núcleo"],["connections","Conexiones y artefactos de apoyo"],["offer","Oferta mínima"],["firstCustomer","Primer cliente o prospecto"]];
const phases=["MAR","Venta","Cierre","Boarding","Operaciones","Postventa"];
const initial={name:"LINK Cupones",pain:"",model:"",buyer:"",seller:"",operator:"",issuer:"",artifact:"",connections:"",offer:"",firstCustomer:"",evidence:[],stage:"germinar",phaseNotes:{},notes:[],status:"embryo"};
function blank(name){return {...initial,name:name.trim(),evidence:[],phaseNotes:{},notes:[]};}
const prompts={DISCOVER:"¿Qué dolor concreto tiene el cliente, quién lo sufre y cómo se resuelve hoy?",DIAGNOSE:"¿Qué capacidad ya existe en LINK y cuál falta para entregar la oferta?",VERIFY:"¿Qué comprobante demuestra una venta real, cobrada y verificable?"};
function guide(d){if(!d.pain)return "Describe primero el problema real que resolverá este negocio.";if(!d.buyer)return "Identifica quién pagaría por resolver ese problema.";if(!d.model)return "Define el modelo económico y la propuesta de valor.";if(!d.artifact)return "Nombra el artefacto mínimo que permite prestar el servicio.";if(!d.offer)return "Define una oferta vendible con precio y alcance.";return "Busca el primer cliente y reúne evidencia de cobro y facturación.";}
export default function GenesisStudio(){
 const [drafts,setDrafts]=useState([blank("LINK Cupones")]),[selected,setSelected]=useState(0),[name,setName]=useState(""),[mode,setMode]=useState("DISCOVER"),[note,setNote]=useState(""),[hydrated,setHydrated]=useState(false);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(STORE)||"null");if(Array.isArray(saved)&&saved.length)setDrafts(saved)}catch{}setHydrated(true)},[]);
 useEffect(()=>{if(hydrated)localStorage.setItem(STORE,JSON.stringify(drafts))},[drafts,hydrated]);
 const d=drafts[selected]||drafts[0];if(!d)return null;
 const edit=(patch)=>setDrafts(prev=>prev.map((v,i)=>i===selected?{...v,...patch}:v));
 const completed=fields.filter(([k])=>Boolean(d[k]?.trim())).length;
 const paid=d.evidence.some(e=>e.kind==="payment"&&e.reference?.trim()&&Number(e.amount)>0&&e.verified===true);
 const billed=d.evidence.some(e=>e.kind==="tax_document"&&e.reference?.trim()&&e.verified===true);
 const graduated=paid&&billed;
 const [proofKind,setProofKind]=useState("payment"),[proofRef,setProofRef]=useState(""),[proofAmount,setProofAmount]=useState("");
 function addProof(){if(!proofRef.trim()||(proofKind==="payment"&&!(Number(proofAmount)>0)))return;edit({evidence:[...d.evidence,{id:crypto.randomUUID(),kind:proofKind,reference:proofRef.trim(),amount:proofKind==="payment"?Number(proofAmount):0,verified:false,createdAt:new Date().toISOString()}]});setProofRef("");setProofAmount("")}
 return <main className="genesisStudio">
 <header className="genesisHead"><div><span className="genesisKicker">LINK WORLD / DIMENSIÓN 00</span><h1>Génesis <span>◉</span></h1><p>Ideas que germinan, capacidades que se ensamblan y negocios que nacen con evidencia.</p></div><div className="genesisBadge">ENTORNO DE PROTOTIPADO · SIN DEPLOY</div></header>
 <div className="genesisGrid"><aside className="genesisAside"><span className="genesisKicker">HUBS / EMBRIONES</span>{drafts.map((v,i)=><button className={"genesisSeed "+(selected===i?"active":"")} key={i} onClick={()=>setSelected(i)}><span>◉</span><b>{v.name}</b><small>{v.status==="embryo"?"En gestación":"Preparado para revisión"}</small></button>)}<form onSubmit={e=>{e.preventDefault();if(!name.trim()||drafts.some(x=>x.name.toLowerCase()===name.trim().toLowerCase()))return;setDrafts(x=>[...x,blank(name)]);setSelected(drafts.length);setName("")}}><input aria-label="Nombre del nuevo embrión" value={name} onChange={e=>setName(e.target.value)} placeholder="Nuevo embrión"/><button type="submit">+ Germinar</button></form><p className="genesisFootnote">Los borradores de esta versión se guardan en este navegador, no en Supabase.</p></aside>
 <section className="genesisCore"><div className="genesisCoreTitle"><span className="genesisKicker">EMBRIÓN / {d.stage.toUpperCase()}</span><h2>{d.name}</h2><p>{guide(d)}</p></div><div className="genesisProgress"><div style={{width:completed/fields.length*100+"%"}}/><span>{completed}/{fields.length} fundamentos</span></div>
 <div className="genesisModes">{["germinar","comprobar","estructurar"].map(s=><button key={s} className={d.stage===s?"active":""} onClick={()=>edit({stage:s})}>{s}</button>)}</div>
 <div className="genesisFields">{fields.map(([key,label])=><label key={key}><span>{label}</span><textarea rows={key==="connections"?3:2} value={d[key]||""} onChange={e=>edit({[key]:e.target.value})} placeholder={"Por definir · "+label.toLowerCase()}/></label>)}</div>
 <h3>Concha · seis etapas</h3><div className="genesisStages">{phases.map((p,i)=><label key={p}><span>{i+1}. {p}</span><textarea rows="2" value={d.phaseNotes?.[p]||""} onChange={e=>edit({phaseNotes:{...d.phaseNotes,[p]:e.target.value}})} placeholder="Capacidad, responsable y evidencia pendiente"/></label>)}</div>
 <section className="genesisProof"><span className="genesisKicker">UMBRAL ECONÓMICO</span><h3>Primera venta comprobada</h3><p>Una propuesta o una factura sin pago no acreditan por sí solas un negocio comprobado. Adjunta referencia de pago y documento tributario; ambos deben validarse por una persona autorizada.</p><div className="genesisProofForm"><select value={proofKind} onChange={e=>setProofKind(e.target.value)}><option value="payment">Comprobante de pago</option><option value="tax_document">Boleta / factura</option></select><input value={proofRef} onChange={e=>setProofRef(e.target.value)} placeholder="Referencia o URL de evidencia"/>{proofKind==="payment"?<input type="number" min="1" value={proofAmount} onChange={e=>setProofAmount(e.target.value)} placeholder="Monto CLP"/>:null}<button onClick={addProof}>Adjuntar para revisión</button></div>{d.evidence.map(e=><p key={e.id} className="genesisEvidence">{e.kind==="payment"?"Pago":"Documento"} · {e.reference} · {e.verified?"Verificado":"Pendiente de verificación"}</p>)}<strong>{graduated?"Evidencia validada: listo para revisión de nacimiento":"Todavía en Génesis · no existe graduación automática"}</strong></section>
 </section>
 <aside className="genesisGuide"><span className="genesisKicker">REA · ARQUITECTURA Y VERIFICACIÓN</span><h3>Conversación de diseño</h3><div className="genesisModes">{["DISCOVER","DIAGNOSE","VERIFY"].map(x=><button key={x} className={mode===x?"active":""} onClick={()=>setMode(x)}>{x}</button>)}</div><p className="genesisPrompt">{prompts[mode]}</p><p>REA aquí funciona como guía de trabajo. La ejecución autónoma y el chat con modelo requieren conectar el servicio real; no se simulan respuestas de IA.</p><textarea value={note} onChange={e=>setNote(e.target.value)} rows="4" placeholder="Registra una decisión, hipótesis o pendiente…"/><button className="genesisSave" onClick={()=>{if(!note.trim())return;edit({notes:[...d.notes,{mode,text:note.trim(),at:new Date().toISOString()}]});setNote("")}}>Guardar conversación de trabajo</button><div className="genesisNotes">{d.notes.slice().reverse().map((n,i)=><div key={i}><small>{n.mode} · {new Date(n.at).toLocaleDateString("es-CL")}</small><p>{n.text}</p></div>)}</div><div className="genesisCapabilities"><span className="genesisKicker">MICELIO / REFINE</span><h3>Capacidades a ensamblar</h3><p>Catálogo de acciones · Formularios · Recursos · Tablas · Evidencias · Permisos.</p><small>Refine: adaptador previsto, aún no conectado. Pulso Vivo: integración pendiente. No se realizan cambios productivos.</small></div></aside></div>
 </main>;
}